
# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: info
  logs:
    custom_components.energytariff: debug

homeassistant:
  allowlist_external_dirs:
    - "/workspaces/energytariff"

sensor:
  - platform: file
    name: "power_usage"
    unit_of_measurement: "W"
    file_path: /workspaces/energytariff/sensor-data.txt

  - platform: energytariff
    entity_id: "sensor.power_usage"
    max_power: 15900
    target_energy: 10
    levels:
      - name: "Trinn 1: 0-2 kWh"
        threshold: 2
        price: 135
      - name: "Trinn 2: 2-5 kWh"
        threshold: 5
        price: 170
      - name: "Trinn 3: 5-10 kWh"
        threshold: 10
        price: 290
      - name: "Trinn 4: 10-15 kWh"
        threshold: 15
        price: 600
      - name: "Trinn 5: 15-20 kWh"
        threshold: 20
        price: 800



# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
